name-template: 'v$RESOLVED_VERSION 🚀'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: ✨ Features'
    labels:
      - 'feature'
  - title: '💪 Enhancement'
    labels:
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    label: 'chore'
  - title: '🔧 Refactoring'
    label: 'refactor'
  - title: '📖 Documentation'
    label: 'documentation'
  - title: '⛓️ Dependency update'
    label: 'dependencies'

template: |
  ## What's Changed

  $CHANGES
