name: Release Drafter for API

on:
  push:
    branches: [main]
    paths:
      - 'api/**'

  pull_request:
    branches: [main]
    paths:
      - 'api/**'

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          config-name: /release-drafter/api-config.yml
